# Generated by Django 4.2 on 2025-04-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
