# Generated by Django 5.1.3 on 2025-04-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usersession_x3dhexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='X3DH_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk', models.TextField()),
                ('spk', models.TextField()),
                ('ad', models.TextField()),
                ('user_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.usersession')),
            ],
        ),
    ]
