# Generated by Django 5.1.3 on 2025-04-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_message_ratchet_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratchet_message',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='RatchetSession',
        ),
        migrations.DeleteModel(
            name='Ratchet_Message',
        ),
    ]
